### ISSUE TITLE
cleanStruct() key scope

### ISSUE THREAD

**Issue by tophersmith143** [jordanclark/cfshipstation#1]
When you have a nested structure and cleanStruct is called again the "key" variable gets overridden replacing the original "key". This results in the last key value getting assigned as structures name. Setting the local scope for "key" will fix this.

`var key = ""; `  

Also on CF11 `value= arguments.input[ key ] ?: ""; ` returns an empty struct for some reason.

**Comment by jordanclark** [comment]
Thank @tophersmith143 for the input on the missing var, I found a few more missing vars and commit those.
